### ISSUE TITLE
Nexus 7 deb + Ubuntu touch devel

### ISSUE THREAD

**Issue by zubozrout** [pseuudonym404/neverball-touch#1] opened 2015-05-28 07:09 UTC
Hello,
I just wanted to share an issue on my Nexus 7 tablet. The game runs I would say pretty fast on my device, as I can hear sounds of various touches on the screen, really responsive, but I can't see anything but junk, distorted image. I can see my application launcher and above it there are transparent 1px lines of various colours.

Probably not your issue but may be a Mir or driver issue.

**Comment by laurie-bradshaw** [comment] 2015-05-30 19:34
Closing as a duplicate of https://github.com/pseuudonym404/neverball-touch/issues/2

**Closed as completed by laurie-bradshaw** 2015-05-30 19:34 UTC
